<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DemoTestSuite3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5d3c9e31-c8fa-45dc-87f6-e0671b2b403b</testSuiteGuid>
   <testCaseLink>
      <guid>9f805b72-02b8-4402-bf6a-0df68cb79577</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/Test4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c32ae20-c7b9-4b88-ab8b-f6bc4349c075</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>860a217a-ce44-45c3-ac1b-9e81a23b46ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c28c4c1d-1d5a-4759-9c1f-97f77d46c2c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/Test6</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49a85032-e30b-4407-9059-343e4f45b187</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76b8ae4e-1b14-4b54-9074-1a1303d3f37f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3469cc43-4424-437a-a960-5d2e35faaa65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Day3/DelayTestCase</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
