<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2a1dc82b-7f7c-4af4-836e-f8f43f9f025e</testSuiteGuid>
   <testCaseLink>
      <guid>b2784c1c-effe-48c1-acf8-706ce7e64a19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/Test6</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c8bce7a7-6b02-44eb-a39e-2a663aff629c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data3</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c8bce7a7-6b02-44eb-a39e-2a663aff629c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>49a85032-e30b-4407-9059-343e4f45b187</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c8bce7a7-6b02-44eb-a39e-2a663aff629c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>76b8ae4e-1b14-4b54-9074-1a1303d3f37f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
